name: Update dependencies

on:
  schedule:
    - cron: '43 3 * * 5'
  # allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Update dependencies
      run: composer update

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run tests
      run: vendor/bin/phpunit

    # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v6
