name: Update dependencies

on:
  schedule:
    - cron: '43 3 * * 5'
  # allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update dependencies
      run: composer update

    - uses: ./.github/workflows/setup-laravel.yml
    - uses: ./.github/workflows/run-phpunit.yml

    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: Update dependencies
